spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:todo_list_manager_test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;DATABASE_TO_UPPER=false
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false

server:
  port: 0

logging:
  level:
    root: WARN
    com.mipt.nikitabumagin: INFO
