package com.mipt.nikitabumagin.dto.mapper;

import com.mipt.nikitabumagin.dto.TaskAttachmentCreateDto;
import com.mipt.nikitabumagin.dto.TaskAttachmentResponseDto;
import com.mipt.nikitabumagin.dto.TaskAttachmentUpdateDto;
import com.mipt.nikitabumagin.model.TaskAttachment;
import org.mapstruct.BeanMapping;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;

@Mapper(componentModel = "spring")
public interface TaskAttachmentMapper {

    /**
     * Converts a TaskAttachmentCreateDto to a TaskAttachment entity.
     *
     * <p>Ignores fields that are generated by the system or managed separately, such as 'id',
     * 'task', 'storedFileName', and 'uploadedAt'. The 'task' field is expected to be set separately
     * after mapping, based on the 'taskId' provided in the DTO.</p>
     *
     * @param dto the DTO containing the data for creating a new attachment
     * @return a TaskAttachment entity with mapped fields from the DTO
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "task", ignore = true)
    @Mapping(target = "storedFileName", ignore = true)
    @Mapping(target = "uploadedAt", ignore = true)
    TaskAttachment toEntity(TaskAttachmentCreateDto dto);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "task", ignore = true)
    @Mapping(target = "storedFileName", ignore = true)
    @Mapping(target = "size", ignore = true)
    @Mapping(target = "uploadedAt", ignore = true)
    TaskAttachment updateEntity(TaskAttachmentUpdateDto dto,
            @MappingTarget TaskAttachment attachment);

    @Mapping(target = "taskId", source = "task.id")
    TaskAttachmentResponseDto toResponseDto(TaskAttachment attachment);
}
