create table tasks (
    id bigint generated by default as identity primary key,
    title varchar(100) not null,
    description varchar(500),
    completed boolean not null default false,
    created_at timestamp not null,
    due_date timestamp,
    priority varchar(16) not null,
    tags text
);

create table task_attachments (
    id bigint generated by default as identity primary key,
    task_id bigint not null,
    file_name varchar(255) not null,
    stored_file_name varchar(255) not null,
    content_type varchar(255),
    size bigint not null,
    uploaded_at timestamp not null,
    constraint fk_task_attachments_task foreign key (task_id) references tasks (id) on delete cascade
);

create index idx_task_attachments_task_id on task_attachments (task_id);
